server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountservice
    username: root
    password: Talgiuyujuseyo12@#12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
